#!/usr/bin/env python3

import os
from sys           import argv
from notion_client import Client

from getToken       import getToken
from reference      import reference
from notion_payload import duplication, addPaper, addChildPage
from database_init  import init
from help           import help


INDEX = os.path.expanduser('~/.notion_token.csv')
FLAG  = 'referenceManager'


narg = len(argv)

if (narg == 1):
    help()

if (argv[1] == 'init'):
    init(INDEX, FLAG)
elif (argv[1] == 'add'):
    if (narg >= 3):
        info = getToken(INDEX, FLAG)
        if ('https://' in info[2].strip()):
            raise ValueError('Invalid page id. Use "thoth init" at first')
        token, page_id, database_id = info[1].strip(), info[2].strip(), info[3].strip()

        notion = Client(auth=token)

        for i in range(2, narg):
            doi = argv[i]

            if (duplication(notion, database_id, doi)):
                continue

            data   = reference(doi)
            status, subpage_id = addChildPage(notion, page_id, data)
            status = addPaper(notion, database_id, subpage_id, data)
    else:
        help()
else:
    help()



